### ISSUE TITLE
eventually-postgres: A not-persisted projection to be able to use in Projector

### ISSUE THREAD

**Issue by to266** [eventually-rs/eventually-rs#139]
**Is your feature request related to a problem? Please describe.**
Currently it seems that it's impossible to create a non-persisted projection from a postgres event store right?

The intended use-case:
 - There are multiple (because potentially a deployment might scale up) in-memory projections, which offer tiny fast materialized views for convenience.
 - If a particular pod gets moved, the projections get restarted, catch up fully, and everything proceeds as expected.

If I understand correctly, a persistent projection would not restart from the beginning, but rather pick up from the last consumed event - meaning the materialized view is incorrect.

**Describe the solution you'd like**
To be able to create a non-persisted projection from a postgres event store. I guess essentially something that implements `eventually::Subscription` trait, so that it can be used in `eventually::Projector`.

**Describe alternatives you've considered**
As I understand now, the intended use-case for a persisted subscription is with projections that are also persisted after updates. I would rather avoid this for now, though.

**Comment by ar3s3ru** [comment]
Hey @to266,
I guess you're describing a [Transient subscription](https://eventually-rs.github.io/eventually-rs/eventually/subscription/struct.Transient.html), which implements both a _Volatile_ (reads from the beginning of the Event Stream) and _Catch-up_ (reads from a specified point in time of the Event Stream) semantics.

In this particular case,
>If a particular pod gets moved, the projections get restarted, catch up fully, and everything proceeds as expected.

I guess you're describing the _Volatile_ semantics (i.e. at each pod restart, the projection starts from the beginning).

You can find an example of it here: https://github.com/eventually-rs/eventually-rs/blob/726250e22e720d471da52132db9038dd134c9eea/eventually-app-example/src/lib.rs#L38-L54

**Comment by to266** [comment]
Thanks for the quick response and example! I had seen it, and tried to make it work, but with both this and the `eventually-postgres` tests I must have gotten confused.

This seems to make the compiler happily.. Does it look correct?
```rust
// <snip>
let aggregate = MyAggregate.as_aggregate();
let store = eventstore_builder
    .for_aggregate(EVENTUALLY_NAME, &aggregate)
    .await?;
let dsn = std::env::var("EVENTUALLY_URL").expect("Eventually url not set");
let subscriber =
    EventSubscriber::<aggregate::Id, aggregate::ProjectEvent>::new(&dsn, EVENTUALLY_NAME)
        .await?;
let subscription = TransientSubscription::new(store.clone(), subscriber);
let this_projection = Arc::new(RwLock::new(MyProjection::default()));
let mut projector = eventually::Projector::new(this_projection.clone(), subscription);
eventually::spawn(async move { projector.run().await.expect("Should not fail") });

```

Also, ideally I'd like to be somewhat robust against the transient subscription dropping connection and then failing, or similar random things.
Have you thought how to restart them, or at least handle creating them again in such cases? Worst case I could crash the whole process and make the pod restart, but I'd rather avoid that if it's not too difficult :+1:

**Comment by ar3s3ru** [comment]
Hey @to266,
your snippet does look correct indeed :+1: 

Related to the second point:

>Also, ideally I'd like to be somewhat robust against the transient subscription dropping connection and then failing, or similar random things.
Have you thought how to restart them, or at least handle creating them again in such cases? Worst case I could crash the whole process and make the pod restart, but I'd rather avoid that if it's not too difficult :+1:

Subscription failure is something I've been thinking about...

In the case of Persistent Subscriptions, this isn't much of a problem since there is checkpointing and is persisted in a durable storage. In the case on "transient" Subscriptions, there are two things missing:
1. Handling a failure coming from the underlying Event Stream (when streaming from the Event Store), e.g. "what should the Subscription do when it receives `SomeError`? Stop the whole thing? Filtering these errors?"
2. Recreate the underlying `Stream` starting from the last checkpointed event.

I think the current design is not great, and I'm trying to come up with a different design for 0.5.0 (sneak peak #140), from how to represent Event Streams -- and how that impacts the Event Store trait --, to how to subscribe to events, projections, process managers, etc.

I value any thoughts in that regard, so feel free to either comment on the aforementioned PR or in #133 :smile: 

For now, I'll close this ticket :+1:
