### ISSUE TITLE
IDs have to be unique across two different Aggregates?

### ISSUE THREAD

**Issue by to266** [eventually-rs/eventually-rs#141]
**Describe the bug**
With in-memory eventstores for aggregate type `A` and aggregate type `B` I can successfully create `root_A` and `root_B` that share the same `id`. All operations behave as expected, and there does not seem to be any data leaking etc.

With `eventually-postgres` eventstore, the two roots cannot share an ID, since the events are stored and collected form the same table (when adding the second one, the repository freaks out a bit, since it receives version 1 instead of version 2, because the two aggregates share an id)

**Expected behavior**
The behavior between the eventstore implementations should be consistent.

Currently I would prefer for different types of aggregates to be able to share identical IDs, but I realize there is a good argument for this behavior :smile:

**Comment by ar3s3ru** [comment]
Hey @to266,
Thanks for reporting the bug!

It looks like the issue is in this particular stored procedure:
https://github.com/eventually-rs/eventually-rs/blob/d241588e83ab7f253788cd6d8cc7fb088d8bc40a/eventually-postgres/src/migrations/V3__append_to_store.sql#L23-L24

The `SELECT` statement should also check against the `aggregate_type_id`. Indeed, two Aggregates sharing the same ID but belonging to two different Aggregate Types should not have any problems on the Event Store.
