### ISSUE TITLE
[Question] Intended usage of `Aggregate`

### ISSUE THREAD

**Issue by lamafab** [eventually-rs/eventually-rs#143]
Hello

Thank you for creating this library, I'm about to use if for my next project. 

While reading the docs, some questions regarding the `Aggregate` came to mind. This is mostly based on intended usage (good design). If I understand it correctly, you can pass a `State` and a `Command` to `Aggregate::handle`, where its logic determines whether events should be created. If events are created, those are applied with `Aggregate::apply` by passing on the `State` and `Event`.

No my question is, where exactly does this `State` come from? Is it from the `EventStore` or an event from another Aggregate? And when `Aggregate::apply` gives you back the new `State`, what do you do with it? Pass it on to `EventStore::append` (which expects `Event`, although implementers can decide what the type is)?

Thanks a lot

**Comment by ar3s3ru** [comment]
Hey @lamafab,
I believe many of your questions might be answered by the [`eventually::aggregate` module documentation](https://eventually-rs.github.io/eventually-rs/eventually/aggregate/index.html).

However, let me try to answer these questions and, if you still feel something missing, check out the aforementioned documentation or our [Gitter chat](https://gitter.im/eventually-rs/community) to ask for support :smile:

---

`Aggregate` is a *consistency boundary*, meaning it is used to enforce/maintain certain business invariants when performing state changes (through `Command`s).

#### Example

An Order is an Aggregate that:
* Has *at least* one Order Item.
* Has a total price greater or equal than 0.00 <currency>.
* When placed, it cannot be changed anymore.

As you might expect, an Order might expose a number of interesting operations, such as:
* Add an Order Item to the Order with a certain quantity
* Remove a certain quantity of an Order Item from the Order
* Place the Order and pay for it (these might also be two separate operations)

The above operations are, in Event Sourcing, expressed through `Command`s.

The whole point of Event Sourcing is that side-effects (the ones `Command`s have on `State`) are not stored as `State` in the database directly (e.g. serializing the `State` in JSON or whatever, and dumping it in a table), but rather as a sequence of Domain Events.

### In `eventually`

`Aggregate` trait is basically an _actor_: implementations of the trait have all the necessary dependencies in order to `handle` `Command`s (e.g. the Order Item repository, from example above) and define:
1. **How** to evaluate a `Command`, given the current `State` of the Aggregate (the `State` is the amount of necessary information needed to verify the business invariants)
2. **How** to transition from the previous `State` of the Aggregate, to the next.

On point 1., this is of course the `handle` method, which basically identifies the necessary changes that have to be done on the `State`, as a result of the `Command` received. (e.g. if the command was `AddOrderItem`, the required change might be to add the Order Item to the items list)

Note: `handle` doesn't return `State`, but it returns `Event`s. Because, as I said before, side-effects are expressed through Domain Events. (e.g. so, in case of `AddOrderItem`, a relevant Domain Event might be `OrderItemWasAdded`).

On point 2., this is the `apply` method. `apply` takes the "current" value of `State` and the next Domain Event to evaluate (again, comes from `handle` operations) and produces the **next** `State`. In functional programming, this is called a _left-fold_.

---

You may now be wondering: "wait, there is `handle` which produces `Event`s; there's `apply` who describes `State` transitions... how the hell are the two connected?!"

#### Aggregate Roots

You **never** -- **NEVER** -- call the `Aggregate` impl directly.

Access to an Aggregate instance happens through an [`AggregateRoot`](https://eventually-rs.github.io/eventually-rs/eventually/aggregate/struct.AggregateRoot.html). An `AggregateRoot` is the "root" point of interaction with an Aggregate instance, which means it's the only object that will handle Commands and update the State: it does so through its own `handle` method:

https://github.com/eventually-rs/eventually-rs/blob/718d9acc473cf731276aec67e6148b163073a7dc/eventually-core/src/aggregate.rs#L281-L301

When the `AggregateRoot` receives a `Command` to handle, it will delegate the operation to the `Aggregate` impl object: https://github.com/eventually-rs/eventually-rs/blob/718d9acc473cf731276aec67e6148b163073a7dc/eventually-core/src/aggregate.rs#L282-L285

The `handle` call will result in some (or none) events produced. If some events have been been produced, the `AggregateRoot` updates its internal `State` and adds those `Event`s to a list of "uncommitted events":

https://github.com/eventually-rs/eventually-rs/blob/718d9acc473cf731276aec67e6148b163073a7dc/eventually-core/src/aggregate.rs#L287-L298

#### Event-sourced Repository

How do you get access to an `AggregateRoot` you ask?

Through a [`Repository`](https://eventually-rs.github.io/eventually-rs/eventually/struct.Repository.html) instance, using the `get` method.

After getting back an `AggregateRoot` instance, and after sending a `Command` to it, you can persist the changes using `Repository::add`. The `Repository` will flush the list of "uncommitted events" from the `AggregateRoot` and call the `EventStore::append` event with the current version of the root for optimistic concurrency control.

---

A bit confused? 

Take a look at the `eventually-app-example` crate to take a look at how this whole flow works. In particular, you can check out this API endpoints to have a better idea:

https://github.com/eventually-rs/eventually-rs/blob/718d9acc473cf731276aec67e6148b163073a7dc/eventually-app-example/src/api.rs#L129-L159

Hope that helped :smile: 

I'm closing this issue since it's a question, and not an issue.
As I said in the beginning, if you need some more help, please reach out on our Gitter chat :wave:

**Comment by lamafab** [comment]
@ar3s3ru Wow, that's one hell of an answer! Thanks a lot.

> You never -- NEVER -- call the Aggregate impl directly.

This should probably be in the type description.
